### ISSUE TITLE
Add garden.ProcessNotFoundError error type

### ISSUE THREAD

**Issue by vito** [cloudfoundry/garden#55]
Now that process IDs can be injected via `(Container).Run`, I'd like to have `(Container).Attach` return this specific error so that I can check for it and know to do `(Container).Run` with the same ID instead. This would allow Concourse to stop tracking this state as properties on the container, and make the reentrancy a lot simpler and less error-prone.

This should also *not* be logged at an error level, just so operators don't see the noise; it's "happy path" to optimistically look for a process to be already running, and would happen multiple times for every build (once per step).

**Comment by jszroberto** [comment]
@vito Garden has being extended to return a new error ProcessNotFoundError when the requested process doesn't exist.

**Comment by vito** [comment]
Yay!
