### ISSUE TITLE
Setting grace time should account for existing client connections

### ISSUE THREAD

**Issue by topherbullock** [cloudfoundry/garden#58]
When investigating concourse/concourse#1269 we found an issue with grace time; specifically when setting the grace time after a client connection is already open.

This can be reproduced using [this fork of gaol](https://github.com/topherbullock/gaol) which supports setting grace time after create. 
Here's the steps:
- `gaol create -n cake -r docker:///alpine`
- `gaol run cake -a -c 'watch date'`
- open a new terminal and `gaol set-gracetime cake -t 10s`
- cry as your cake is ripped from your grasp

Conversely:
- `gaol create -n cake -g 10s -r docker:///alpine`
- `gaol run cake -a -c 'watch date'`
- enjoy your cake as long as you want

Pedantically [ referencing the docs ](https://github.com/cloudfoundry/garden/blob/master/client.go#L69-L70), they say it containers with a grace time set will be destroyed after being "unreferenced by any client connection". But in practice, only *new* connections after grace time has been set are accounted for.

**Comment by williammartin** [comment]
Yep, I can totally see this in the code. I didn't even know setting grace time after creation was something we allowed! 

On setting the Grace time we `defuse` the old bomb (if there was one):

https://github.com/cloudfoundry/garden/blob/master/server/request_handling.go#L716-L718

but `pause` is associated with a specific bomb:

https://github.com/cloudfoundry/garden/blob/master/server/bomberman/bomberman.go#L100-L105

so when we strap a new bomb:

https://github.com/cloudfoundry/garden/blob/master/server/request_handling.go#L719

it starts ticking.

@julz WDYT? The original story didn't deal with this in acceptance https://www.pivotaltracker.com/story/show/101620462 but it does seem like something we should fix. I can't really think of a use case for the current behaviour.
